// This file is included in GLSL and C++ sources

// maximum of 32 render options
#define RENDER_OPTION_TXAA 1<< 0
#define RENDER_OPTION_GAMMA_CORRECTION 1<< 1
#define RENDER_OPTION_HDR_TONE_MAPPING 1<< 2
#define RENDER_OPTION_HARD_SHADOWS 1<< 3
#define RENDER_OPTION_REFLECTIONS 1<< 4

// maximum of 32 debug options
#define DEBUG_OPTION_WIREFRAME 1<< 0
#define DEBUG_OPTION_PHYSICS 1<< 1

// Limits
#define MAX_ACTIVE_LIGHTS 16

// Render modes
#define RENDER_MODE_NOTHING 0
#define RENDER_MODE_STANDARD 1
#define RENDER_MODE_NORMALS 2
#define RENDER_MODE_ALBEDO 3
#define RENDER_MODE_EMISSION 4
#define RENDER_MODE_DEPTH 5
#define RENDER_MODE_DISTANCE 6
#define RENDER_MODE_METALLIC 7
#define RENDER_MODE_ROUGNESS 8
#define RENDER_MODE_REFRACTION 9

// C++ Only, within this module only
#ifdef V4D_RAYTRACING_RENDERER_MODULE
namespace RENDER_OPTIONS {
	bool HARD_SHADOWS = true;
	bool TXAA = true;
	bool HDR_TONE_MAPPING = true;
	bool GAMMA_CORRECTION = true;
	bool REFLECTIONS = true;
	
	uint32_t Get() {
		uint32_t flags = 0;
		if (HARD_SHADOWS) flags |= RENDER_OPTION_HARD_SHADOWS;
		if (TXAA) flags |= RENDER_OPTION_TXAA;
		if (HDR_TONE_MAPPING) flags |= RENDER_OPTION_HDR_TONE_MAPPING;
		if (GAMMA_CORRECTION) flags |= RENDER_OPTION_GAMMA_CORRECTION;
		if (REFLECTIONS) flags |= RENDER_OPTION_REFLECTIONS;
		return flags;
	}
}
namespace DEBUG_OPTIONS {
	bool WIREFRAME = false;
	bool PHYSICS = false;
	
	uint32_t Get() {
		uint32_t flags = 0;
		if (WIREFRAME) flags |= DEBUG_OPTION_WIREFRAME;
		if (PHYSICS) flags |= DEBUG_OPTION_PHYSICS;
		return flags;
	}
}
#endif


// Attributes to use for geometry creation (multiple can be used together)
#define GEOMETRY_ATTR_PRIMARY_VISIBLE 1<< 0
#define GEOMETRY_ATTR_CAST_SHADOWS 1<< 1
#define GEOMETRY_ATTR_REFLECTION_VISIBLE 1<< 2
#define GEOMETRY_ATTR_COLLIDER 1<< 3
// Only one of the following can be used
#define GEOMETRY_ATTR_SOLID 1<< 4
#define GEOMETRY_ATTR_WATER 1<< 5
#define GEOMETRY_ATTR_FOG 1<< 6
#define GEOMETRY_ATTR_ATMOSPHERE 1<< 7

// Masks to use for ray-tracing calls
#define RAY_TRACE_MASK_PRIMARY			GEOMETRY_ATTR_PRIMARY_VISIBLE
#define RAY_TRACE_MASK_SHADOWS			GEOMETRY_ATTR_CAST_SHADOWS
#define RAY_TRACE_MASK_REFLECTION		GEOMETRY_ATTR_REFLECTION_VISIBLE
#define RAY_TRACE_MASK_IN_SPACE			GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER|GEOMETRY_ATTR_FOG|GEOMETRY_ATTR_ATMOSPHERE
#define RAY_TRACE_MASK_IN_ATMOSPHERE	GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER|GEOMETRY_ATTR_FOG
#define RAY_TRACE_MASK_IN_FOG			GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER
#define RAY_TRACE_MASK_IN_WATER			GEOMETRY_ATTR_SOLID


