#pragma once

// #define ZAP_USE_REINTERPRET_CAST_INSTEAD_OF_MEMCPY
// #define EVENT_DEFINITIONS_VARIADIC

// Logger
#define LOGGER_INSTANCE v4d::io::Logger::ConsoleInstance()

// #define RENDER_SECONDARY_IN_ANOTHER_THREAD

#define APP_NETWORKING_DEFAULT_SOLO_PORT 12345

#define APP_NETWORKING_USE_RSA_KEY

